name: Next.js CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build locally in GitHub Actions
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
      - name: Start the application using PM2
        run: npm start
        
