name: Next.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build locally in GitHub Actions
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Deploy to Remote Ubuntu Server
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ./
            git pull
            npm install
            npm run build
            pm2 restart ecosystem.config.js 
